// Titles seen on EBTH and the category each should land in. Add a line here whenever a title is found in the wrong place.
export const GOLDEN = [
  ["Loose 3.00 CT Lab Grown Diamond with IGI Report", "Lab-grown stones and jewelry"],
  ["14K 5.32 CTW Lab Grown Diamond Eternity Band", "Lab-grown stones and jewelry"],
  ["Loose 1.05 CTW Lab Grown Diamond Lot", "Lab-grown stones and jewelry"],
  ["Loose 1.50 CT Diamond with GIA Report", "Loose stones"],
  ["Loose 2.06 CT Sapphire", "Loose stones"],
  ["Loose 3.90 CTW Tanzanite Lot", "Loose stones"],
  ["Late Art Deco 14K 2.12 CTW Diamond Ring", "Jewelry, gold"],
  ["1950s 14K 2.19 CTW Diamond Ring", "Jewelry, gold"],
  ["18K 3.40 CT Emerald and Diamond Ring with GIA Report", "Jewelry, gold"],
  ["Ippolita Mini Jet Set 18K and Diamond Drop Earrings", "Jewelry, gold"],
  ["Ever Us 14K Two-Tone 1.62 CTW Diamond Ring", "Jewelry, gold"],
  ["14K Glass Charm Pendant", "Jewelry, gold"],
  ["14K 4.05 CTW Diamond Bracelet", "Jewelry, gold"],
  ["14K Filled Corundum and Diamond Rose Gold Ring with White Gold Mountings", "Jewelry, gold"],
  ["Chromia 18K 8.89 CT Emerald and 0.52 Diamond Enhancer Pendant on Necklace", "Jewelry, gold"],
  ["Sterling Topaz and Sapphire Flamingo Earrings", "Jewelry, silver"],
  ["Sterling Quartz Earrings", "Jewelry, silver"],
  ["Sterling Diamond Band", "Jewelry, silver"],
  ["Sterling Diamond Claddagh Ring with 10K Accent", "Jewelry, silver"],
  ["Tiffany & Co. Return to Tiffany Sterling Round Tag Charm Bracelet", "Jewelry, silver"],
  ["Italian Sterling Herringbone Chain Necklace & Bracelet Set", "Jewelry, silver"],
  ["950 Silver Malachite Jewelry and Sterling Earrings", "Jewelry, silver"],
  ["Sterling Double Headed Tiger Bracelet", "Jewelry, silver"],
  ["Rudy Willie for D'Anz Limited Sterling Coral, Turquoise, & Lapis Cuff Bracelet", "Jewelry, Southwest"],
  ["Western Sterling Turquoise and Scalloped Earrings", "Jewelry, Southwest"],
  ["Gary Reeves Navajo Diné Sterling Stampwork Pendant", "Jewelry, Southwest"],
  ["Eddy Chaco Navajo Diné Concho Ring", "Jewelry, Southwest"],
  ["Signed Navajo Diné Sterling Silver and Black Leather Concho Belts", "Jewelry, Southwest"],
  ["Signed Southwestern Sterling Turquoise and Coral Inlay Cuff Bracelet", "Jewelry, Southwest"],
  ["Western Bear Necklace Featuring Magnesite and Turquoise", "Jewelry, Southwest"],
  ["Darin Bill Navajo Diné Sterling & Gold-Filled Stampwork Band", "Jewelry, Southwest"],
  ["Platinum Pearl Ring", "Jewelry, other"],
  ["Curb Chain Bracelet", "Jewelry, other"],
  ["Mikimoto Matinee Length Pearl Necklace with 18K Clasp", "Jewelry, other"],
  ["Susan Shaw Equestrian Necklace and Earrings", "Jewelry, other"],
  ["Chanel Glass Pearl, Crystal and Resin Clip Earrings, 1988", "Jewelry, other"],
  ["Hermès Quadruple Wrap Leather Bracelet with Silver Tone Buckle", "Jewelry, other"],
  ["Uncommon Discoveries: Jewelry Collection", "Jewelry, other"],
  ["Rolex Lady-Datejust 69173 Neo-Vintage Automatic Watch c.1987", "Watches"],
  ["Collection of Watch Fobs Featuring 9K Gold and Gold Filled Chains and Clasp", "Jewelry, gold"],
  ["Vintage Elks Lodge 14K Ruby, Enamel and Elk Bugle Watch Chain with Fob", "Jewelry, gold"],
  ["Sterling Silver Watch Fob with Masonic Emblem", "Jewelry, silver"],
  ["1903 Waltham Gold Filled Size 18 Pocket Watch with Chain and Fob", "Watches"],
  ["2008 Omega Seamaster Diver Co-Axial Steel Automatic Date Watch", "Watches"],
  ["Cartier Must de Cartier Vermeil Tri-Color Dial Quartz Watch Ref. 3-66001", "Watches"],
  ["Van Teal Deco Revival Amphora Ceramic Table Lamp with Lucite Accents", "Lighting"],
  ["Pair of Imperial Style Porcelain and Metal Table Lamps and Silk Bespoke Shades", "Lighting"],
  ["Crystal Elongated Lamp Prisms", "Lighting"],
  ["Wrought Iron Floor Lamp with Spiral Woven Shade", "Lighting"],
  ["Chanel Mini Round Ribbon Chain Crossbody Bag in Quilted Lambskin Leather", "Handbags and fashion"],
  ["Louis Vuitton Keepall 55 in Monogram Canvas and Vachetta Leather, Vintage", "Handbags and fashion"],
  ["Cartier Panthère Black Leather Shoulder Tote Bag", "Handbags and fashion"],
  ["Hermès Early Issue Forets Scarf 90 in Silk Twill with Box", "Handbags and fashion"],
  ["Stetson 4X Beaver Felt The Open Road Cowboy Hat", "Handbags and fashion"],
  ["MCM Brass Monogram Keychain", "Handbags and fashion"],
  ["Emilio Pucci Pink Cashmere Blend Sleeveless V-Neck Top", "Handbags and fashion"],
  ["Assorted Havana and Horn-Rimmed Prescription Eyeglasses", "Handbags and fashion"],
  ["Christian Dior Institute White Towel Robe with Box", "Handbags and fashion"],
  ["Eunice Katz Stylized Portrait Oil Painting of Woman Cooking", "Art"],
  ["Leo Raymond Ostrenga Oil Portrait of Man in Red Scarf, 20th Century", "Art"],
  ["After Zamy Steynovitz Giclée Print of Two Lovers, Late 20th to 21st Century", "Art"],
  ["Howard Terpning Offset Lithograph Capture of the Horse Bundle, 1993", "Art"],
  ["Beatien Yazz Gouache Painting of Native American Family on Horse, 1986", "Art"],
  ["Amedeo Modigliani Graphite Drawing Two Figures, 1916", "Art"],
  ["Boris Kutchukov Burl Wood Carving of Dog, 2000", "Art"],
  ["Ney Cardoso Cubistic Oil Painting of Guitarist, 1992", "Art"],
  ["Tripartite Chromolithograph Theatre Poster Little Eva's Temptation", "Art"],
  ["Ancient Roman Provincial Æ29 Coin of Trebonianus Gallus, ca. 252 A.D.", "Coins, stamps and currency"],
  ["Five Different Morgan Silver Dollars", "Coins, stamps and currency"],
  ["1947 Panama Silver One Balboa", "Coins, stamps and currency"],
  ["Roll of Twenty 2016 American Silver Eagle 1-Oz. Bullion Coins", "Coins, stamps and currency"],
  ["Very Large Group of Colorano Silk First Day Covers", "Coins, stamps and currency"],
  ["U.S. Airmail Postage Stamp Collection, Scott C1 to C31, MNH", "Coins, stamps and currency"],
  ["1933 USS Macon Graf Zeppelin Postal Cover, Christening", "Coins, stamps and currency"],
  ['Signed "Somebody Stole the Cornbread from My Dressing" by Elizabeth Heiskell', "Books, maps and ephemera"],
  ["First Edition The Secret History by Donna Tartt and More Fiction Books", "Books, maps and ephemera"],
  ["Highway and Other Vintage Travel Maps of the Continental United States", "Books, maps and ephemera"],
  ["Antique University of Pennsylvania Medical School Ephemera, 18th/19th C.", "Books, maps and ephemera"],
  ["Pre-Columbian Jalisco Bichrome Terracotta Figure, circa 200 BCE-300 CE", "Antiquities and natural history"],
  ["18th Dynasty Ancient Egyptian Carved Diorite Scarab, circa 1500-1300 BCE", "Antiquities and natural history"],
  ["Carlos Dunlap San Ildefonso Black on Black Vessel Vase", "Native American, tribal and folk art"],
  ["Artist Signed Longhair Maiden Hand-Carved Hopi Kachina", "Native American, tribal and folk art"],
  ["Mexican Handcrafted Huichol Beaded Wall Hanging Snake", "Native American, tribal and folk art"],
  ["5'1 x 7'8 Hand-Knotted Indian Contemporary Area Rug", "Rugs and textiles"],
  ["2'7 x 4' Hand-Hooked Folk Art Wool Accent Rug", "Rugs and textiles"],
  ["Turkish Overdyed Handwoven Rug Faced Pillow Covers", "Rugs and textiles"],
  ["Christofle Silver Plate Bowl with Silver Plate Cocktail Tray and Round Platter", "Decorative objects"],
  ["Sterling Silver Pitcher with Handle", "Sterling and silver"],
  ["Henry Birks Sterling Pitcher", "Sterling and silver"],
  ["Noritake Valhalla Bone China Dinnerware", "Ceramics and glass"],
  ["Waterford Crystal Seahorse Spirit Decanter", "Ceramics and glass"],
  ["Murano Glass Tortoiseshell Pattern Console Bowl", "Ceramics and glass"],
  ["Pewabic Pottery Lovebirds High Relief Ceramic Tile, 2010", "Ceramics and glass"],
  ["Antique Ottoman Turkish Iznik Plate, 16th/17th Century", "Ceramics and glass"],
  ["Flare Neck Art Glass Vase", "Ceramics and glass"],
  ["Tibetan Himalayan Copper and Brass Amulet Box, Late 19th/Early 20th Century", "Asian art"],
  ["Two Forever Collectibles Bobbleheads of Stan Musial and Bob Feller", "Collectibles and memorabilia"],
  ["Pokémon Card Collection", "Collectibles and memorabilia"],
  ["Ty Derby Slowpoke Canyon and More Beanie Babies", "Collectibles and memorabilia"],
  ["Montblanc Great Characters Muhammad Ali Special Edition Fountain Pen", "Collectibles and memorabilia"],
  ["Frank Sinatra, Michael Jackson, Fleetwood Mac and More 12 Records", "Collectibles and memorabilia"],
  ["Cold Painted Cast Iron Train Locomotive and Coal Tender", "Collectibles and memorabilia"],
  ["Vintage Ihagee Exakta 35mm Camera with Camera Accessories", "Cameras, music and electronics"],
  ["Onkyo D-N3XA Bookshelf Speaker Pair with FM Stereo/AM Tuner Amplifier & More", "Cameras, music and electronics"],
  ["Tasco 10x25, Vivitar 8x, and Belmont 20x50 Binoculars", "Cameras, music and electronics"],
  ["Upholstered Roll-Arm Sofa with Accent Pillows, Late 20th to Early 21st Century", "Furniture"],
  ["Lexington Glass Top Mahogany Accent Table, Late 20th Century", "Furniture"],
  ["Herman Miller Aeron Office Chair", "Furniture"],
  ["Wooden Framed Rectangular Wall Mirror", "Furniture"],
  ["Neoclassical Marble Column Pedestal", "Furniture"],
  ["M.C. Lilley Model 1902 U.S. Army Officer's Saber with Horn Grip, Early 20th C.", "Tools, sporting and military"],
  ["Kabir Kouba Wooden Snowshoes, Mid to Late 20th Century", "Tools, sporting and military"],
  ["Frost Cutlery Sharkfin Folder and Other Knives", "Tools, sporting and military"],
  ["All American Ladder 6' Aluminum Step Ladder", "Kitchen and household"],
  ["Rustic Copper Boiler Wash Tub with Lid", "Kitchen and household"],
  ["Victorian Style Gilded Metal Scrolled Cherub Mantel Clock, Vintage", "Decorative objects"],
  ["Old King Cole Papier-mâché Santa Claus Figurine, Mid-20th Century", "Decorative objects"],
  ["Pierced Brass Medallion and Other Cast Metal Andirons", "Decorative objects"],
  ["Godinger Silver Plate Embossed Jewelry Box and Neiman Marcus Decorative Bowls", "Decorative objects"],
  // found wrong on the live titles, then fixed
  ["Manolo Blahnik Pointed-Toe Ankle Strap Textile Pumps", "Handbags and fashion"],
  ["Dolce & Gabbana Sheer Lace Front V-Neck and Ribbed Virgin Wool Cardigan", "Handbags and fashion"],
  ["Per Se Rex Rabbit Fur Shawl Collar Flat Weave Capelet", "Handbags and fashion"],
  ["White Denim Jeans from Fabrizio Gianni and Paige Denim", "Handbags and fashion"],
  ["Red and Gold Jacquard Tasseled Throw Pillows", "Rugs and textiles"],
  ["Glass Knob Handle and Capstick Wooden Canes, Mid to Late 20th Century", "Collectibles and memorabilia"],
  ["Trompe-l'Oeil Leather Faux Book Round Accent Cabinet, Late 20th Century", "Furniture"],
  ["Jacobean Style Wooden Bench, 20th Century", "Furniture"],
  ["The Bombay Company Empire Style Illuminated Étagère", "Furniture"],
  ["Three Great Britain Silver Half Crowns", "Coins, stamps and currency"],
  ["Ten Proof Jefferson Nickels, 1956 and 1958", "Coins, stamps and currency"],
  ["1909 VDB Lincoln Wheat Cent", "Coins, stamps and currency"],
  ["1863 Civil War Merchant Token", "Coins, stamps and currency"],
  ["Unused Vintage Pre-Stamped Vintage Postal Stationery", "Coins, stamps and currency"],
  ["Pearl Necklace with 14K Clasp", "Jewelry, other"],
  ["14K Bullhorn Charm", "Jewelry, gold"],
  ["Sterling Moissanite Ring", "Lab-grown stones and jewelry"],
  ["Glass Peacocks, Bulbs, and More Christmas Tree Ornaments", "Decorative objects"],
  ["Valley Forge Flag Co. American Flag", "Decorative objects"],
  ["Henry Troemner Antique Apothecary Scales", "Decorative objects"],
  ["Taxidermy Moose Shoulder Mount, Late 20th Century", "Antiquities and natural history"],
  ["Papua New Guinea Auger Shell and Beadwork with Braided Bib", "Native American, tribal and folk art"],
  ["Death NYC Pop Art Graphic Print Homage to Monopoly X Andy Warhol, 2025", "Art"],
  ["Keisuke Serizawa Woodblock Calendar Page November, 1969", "Art"],
  ["Robert Fabe Halftone Pensive Child", "Art"],
  ["Alfred Henry Maurer Oil on Paperboard Fauvist Landscape, 1908–1911", "Art"],
  ['"Cartier: Paris, Londres, New York" by François Chaille, 2014', "Books, maps and ephemera"],
  ['The Metropolitan Museum of Art "Dangerous Liaisons" Exhibition Catalog', "Books, maps and ephemera"],
  ["Oxford Edition Poetical Works of Shelley and Wordsworth, 1906-1907", "Books, maps and ephemera"],
  ["Mid-Century Bubble Stem Martini Glasses", "Ceramics and glass"],
  ["Black Rotary Dial Telephone, Mid 20th Century", "Cameras, music and electronics"],
  ["Netgear Orbi Satellite Routers and Eero B010001 Wi-Fi Router", "Cameras, music and electronics"],
  ["Black + Decker Firestorm Power Tool Kit with Ridgid Shop Vac", "Tools, sporting and military"],
  ["Mid-Century English Willow Cricket Bats", "Tools, sporting and military"],
  ["Huffy Panama Jack Lime Green Step-Through Cruiser", "Tools, sporting and military"],
  ["Brunswick Bart Simpson and Darth Vader Novelty Bowling Balls", "Collectibles and memorabilia"],
  ["Marbled Resin Chessboard with Poker Chip Carousels", "Collectibles and memorabilia"],
  ["Brot-Max Guillotine Style Bread Slicer, Vintage", "Kitchen and household"],
  ["German and Japanese Bisque and Composition Miniature Dolls", "Ceramics and glass"],
  ["Postmodern Metal and Glass Dining Table, Late 20th Century", "Furniture"],
  ["French Neoclassical Style Glass-Top Coffee Table with Lower Shelf", "Furniture"],
  ["Mid Century Modern Two-Tone Record Cabinet, 20th Century", "Furniture"],
  ["Chinese Style Carved Hardwood Settee Bench with Brocade Upholstery", "Furniture"],
  ["Maisto, Motor Max and More Diecast Cars, Late 20th/Early 21st Century", "Collectibles and memorabilia"],
  ["Hand-Painted Embossed Floral Composition of Calla Lilies", "Art"],
];
